// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kaemruhmrbhgmdwbogux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthZW1ydWhtcmJoZ21kd2JvZ3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDg4MzIsImV4cCI6MjA3MDIyNDgzMn0.RZayxSWeLD12MRSzKRfSK21Ah0rVfXlAsX9z7tRTQqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});